# Generated by Django 5.1.3 on 2024-11-29 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Created At Help', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At Help', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('host', models.CharField(max_length=100, verbose_name='ホスト')),
                ('post', models.PositiveSmallIntegerField(default=25, verbose_name='ポート')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ユーザー名')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='パスワード')),
                ('use_tls', models.BooleanField(default=False, verbose_name='TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL')),
            ],
            options={
                'verbose_name': 'サーバー',
                'verbose_name_plural': 'サーバー',
            },
        ),
    ]
